#!/usr/bin/env python2
from argparse import ArgumentParser
import sys

def main(args):
    return 0

if __name__ == '__main__':
    parser = ArgumentParser('get-path-conditions')
    args = parser.parse_args()
    sys.exit(main(args))
