#!/usr/bin/env python2.7
import subprocess
import argparse
import json
import sys
import os

LLDB_COMMAND = os.path.dirname(os.path.realpath(__file__))+"/debugger %s \"%s\""

def main(args):
  infile,m = (args.file,subprocess.check_output(LLDB_COMMAND % (args.file, args.program), shell=True))
  newstack = []
  b = m.split("\n")
  start1 = False
  start = False
  for i in b[2:]:
    iu = i.strip().rstrip()
    ij = iu.find("thread backtrace all")
    if ij != -1:
      start1 = True
      continue
    if start1 == True:
      if iu.find("thread #") != -1:
        start = True
        continue
    if len(iu) > 0 and (iu[0] == '#' or iu[0] == '*') and start == True:
      a = iu.find("#")
      newstack.append(iu[a+1:])
  umap = {}
  umap['file'] = args.file
  umap['stack'] = newstack
  print json.dumps(umap)
  return 0

if __name__ == '__main__':
  parser = argparse.ArgumentParser("getstacks")
  parser.add_argument("program", type=str)
  parser.add_argument("file", type=str, help="input file")
  args = parser.parse_args()
  sys.exit(main(args))
